[package]
name = "core"
version = "1.0.0"

[addresses]
supra_oracle = "0x987654321"


[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = "4988b626feabda147077bc02cba939b7220073ce"
subdir = "aptos-move/framework/supra-framework"

