[package]
name = "core"
version = "1.0.0"

[addresses]
supra_oracle = "0x4d32537c4e7773cda63e2594bf2134c379b510c2dd9a68c2dfe53c7abccc61ba"


[dependencies.SupraFramework]
git = "https://github.com/Entropy-Foundation/aptos-core.git"
rev = 'dev'
subdir = "aptos-move/framework/supra-framework"

